export const selectUser = state => state.auth.user;
export const selectWallet = state => state.auth.user.wallet;
export const selectToken = state => state.auth.token;
export const selectIsLoading = state => state.auth.isLoading;
export const selectError = state => state.auth.error;
export const selectIsFetching = state => state.auth.isFetching;
export const selectIsAuth = state => state.auth.isAuth;
export const selectUserName = state => state.auth.user.name;
export const selectUserEmail = state => state.auth.user.email;